#!/usr/bin/env python3
"""
midi_writer.py - Convert Music Companion JSON to MIDI file

This script reads the JSON output from Picat's companion.pi and
creates a playable MIDI file.

Usage:
    python midi_writer.py session.json session.mid
    python midi_writer.py session.json  # outputs session.mid

Requirements:
    pip install midiutil
"""

import json
import sys
from pathlib import Path

try:
    from midiutil import MIDIFile
except ImportError:
    print("Error: midiutil is required. Install with: pip install midiutil")
    sys.exit(1)


def json_to_midi(json_path: str, midi_path: str) -> None:
    """Convert a Music Companion JSON file to MIDI."""

    # Load JSON data
    with open(json_path, 'r') as f:
        data = json.load(f)

    notes = data['notes']
    tempo_changes = data['tempo_changes']
    metadata = data.get('metadata', {})

    print(f"Converting {json_path} to MIDI...")
    print(f"  Notes: {len(notes)}")
    print(f"  Tempo changes: {len(tempo_changes)}")

    # Create MIDI file (1 track)
    # Use deinterleave=False to avoid issues with overlapping notes
    midi = MIDIFile(1, deinterleave=False)
    track = 0
    channel = 0
    time = 0  # Start at beginning

    # Set track name
    midi.addTrackName(track, 0, "Music Companion")

    # Default tempo (will be overwritten by first tempo change)
    initial_tempo = 120
    if tempo_changes:
        initial_tempo = tempo_changes[0]['bpm']
    midi.addTempo(track, 0, initial_tempo)

    # Build a tempo map: bar -> tempo
    tempo_map = {}
    for tc in tempo_changes:
        tempo_map[tc['bar']] = tc['bpm']

    # Track current tempo for tempo change events
    current_tempo = initial_tempo
    added_tempos = {0}  # Track which beat positions have tempo changes

    # Convert notes to MIDI events
    # We need to calculate absolute time in beats
    beats_per_bar = 4  # Assuming 4/4 time

    for note in notes:
        pitch = note['pitch']
        dur_num = note['dur_num']
        dur_den = note['dur_den']
        bar = note['bar']
        beat = note['beat']
        sub = note.get('sub', 0)
        velocity = note['velocity']

        # Calculate start time in beats (0-indexed)
        start_beat = (bar - 1) * beats_per_bar + (beat - 1) + sub

        # Calculate duration in beats
        # duration is a fraction of a whole note (4 beats in 4/4)
        duration_beats = (dur_num * beats_per_bar) / dur_den

        # Check for tempo change at this bar
        if bar in tempo_map and start_beat not in added_tempos:
            new_tempo = tempo_map[bar]
            if new_tempo != current_tempo:
                midi.addTempo(track, start_beat, new_tempo)
                current_tempo = new_tempo
                added_tempos.add(start_beat)

        # Add note
        midi.addNote(track, channel, pitch, start_beat, duration_beats, velocity)

    # Write MIDI file
    with open(midi_path, 'wb') as f:
        midi.writeFile(f)

    print(f"  Output: {midi_path}")
    print("Done!")


def print_usage():
    """Print usage information."""
    print("Usage: python midi_writer.py <input.json> [output.mid]")
    print()
    print("Convert Music Companion JSON to MIDI file.")
    print()
    print("Arguments:")
    print("  input.json   JSON file generated by Picat companion.pi")
    print("  output.mid   Output MIDI file (default: same name as input)")
    print()
    print("Examples:")
    print("  python midi_writer.py session.json session.mid")
    print("  python midi_writer.py session.json")


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print_usage()
        sys.exit(1)

    if sys.argv[1] in ['-h', '--help']:
        print_usage()
        sys.exit(0)

    json_path = sys.argv[1]

    # Determine output path
    if len(sys.argv) >= 3:
        midi_path = sys.argv[2]
    else:
        # Use same name with .mid extension
        midi_path = str(Path(json_path).with_suffix('.mid'))

    # Validate input file exists
    if not Path(json_path).exists():
        print(f"Error: Input file not found: {json_path}")
        sys.exit(1)

    json_to_midi(json_path, midi_path)


if __name__ == '__main__':
    main()
